# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace
# append to the history file, don't overwrite it
shopt -s histappend
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Shell completion
if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Common configuration, find best configuration dir
SHELL_CONFIG_DIR=""
# Try $0 if the file has been directly source'd
if [ "$(basename $0)" = ".bashrc" -a -d "$(dirname $0)/.shell" ] ; then
    SHELL_CONFIG_DIR="$(dirname $0)/.shell"
elif [ "$(basename $0)" = "bashrc" -a -d "$(dirname $0)/shell" ] ; then
    SHELL_CONFIG_DIR="$(dirname $0)/.shell"
elif [ -n "$SUDO_USER" ] ; then
    SUDO_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
    SHELL_CONFIG_DIR="$SUDO_HOME/.shell"
    unset SUDO_HOME
fi
# Fallback to home directory
if [ -z "$SHELL_CONFIG_DIR" -o ! -d "$SHELL_CONFIG_DIR" ] ; then
    SHELL_CONFIG_DIR="$HOME/.shell"
fi
# Source configuration files
for FILE in aliases environment prompt ; do
    if [ -f "$SHELL_CONFIG_DIR/$FILE" ]; then
        . "$SHELL_CONFIG_DIR/$FILE"
    fi
done
unset SHELL_CONFIG_DIR FILE
