#! perl -w
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2015-2018 Nicolas Iooss
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Make it possible to call some shell commands from key shortcuts
# Requires wmctrl for the fullscreen command

sub on_user_command {
    my ($self, $cmd) = @_;

    # Use wmctrl to toggle the fullscreen status of the current window
    # Command from: https://aur.archlinux.org/packages/urxvt-fullscreen/
    if ($cmd eq "keycmd:togglefull") {
        qx/wmctrl -r :ACTIVE: -b toggle,fullscreen/;
        return;
    }

    # Open a new terminal window with the same current directory
    if ($cmd eq "keycmd:newwindow") {
        chomp(my $shell_pid = qx/pgrep -oP $$/);
        if ($shell_pid eq "") {
            $shell_pid = 'self';
        }
        # Change to the directory referenced by /proc/PID/cwd close any open
        # file descriptor and launch urxvt.
        system(<<"EOF"
            bash -c '
                cd -P /proc/$shell_pid/cwd &&
                for FD in \$(ls -1 /proc/\$\$/fd) ; do
                    test \"\$FD\" -le 2 || eval \"exec \$FD>&-\" ;
                done &&
                (urxvt & disown)'
EOF
        );
        return;
    }
}
