# Use http://lint.travis-ci.org/ to check the syntax of this file

language: python

matrix:
  include:
    # Ubuntu 20.04 LTS (Focal Fossa)
    - os: linux
      dist: focal
      python: "3.9"
      env: BUILDENV=ubuntu2004-focal-python3.9
    - os: linux
      dist: focal
      python: "3.8"
      env: BUILDENV=ubuntu2004-focal-python3.8
    - os: linux
      dist: focal
      python: "3.7"
      env: BUILDENV=ubuntu2004-focal-python3.7
    - os: linux
      dist: focal
      python: "3.6"
      env: BUILDENV=ubuntu2004-focal-python3.6
    - os: linux
      dist: focal
      python: "2.7"
      env: BUILDENV=ubuntu2004-focal-python2.7

    # Ubuntu 18.04 LTS (Bionic Beaver)
    - os: linux
      dist: bionic
      python: "3.8"
      env: BUILDENV=ubuntu1804-bionic-python3.8
    - os: linux
      dist: bionic
      python: "3.7"
      env: BUILDENV=ubuntu1804-bionic-python3.7
    - os: linux
      dist: bionic
      python: "3.6"
      env: BUILDENV=ubuntu1804-bionic-python3.6
    - os: linux
      dist: bionic
      python: "2.7"
      env: BUILDENV=ubuntu1804-bionic-python2.7

    # Ubuntu 16.04 LTS (Xenial Xerus)
    - os: linux
      dist: xenial
      python: "3.8"
      env: BUILDENV=ubuntu1604-xenial-python3.8
    - os: linux
      dist: xenial
      python: "3.7"
      env: BUILDENV=ubuntu1604-xenial-python3.7
    - os: linux
      dist: xenial
      python: "3.6"
      env: BUILDENV=ubuntu1604-xenial-python3.6
    - os: linux
      dist: xenial
      python: "3.5"
      env: BUILDENV=ubuntu1604-xenial-python3.5
    - os: linux
      dist: xenial
      python: "3.4"
      env: BUILDENV=ubuntu1604-xenial-python3.4
    - os: linux
      dist: xenial
      python: "2.7"
      env: BUILDENV=ubuntu1604-xenial-python2.7

    # Ubuntu 14.04 LTS (Trusty Tahr)
    - os: linux
      dist: trusty
      python: "3.6"
      env: BUILDENV=ubuntu1404-trusty-python3.6
    - os: linux
      dist: trusty
      python: "3.5"
      env: BUILDENV=ubuntu1404-trusty-python3.5
    - os: linux
      dist: trusty
      python: "3.4"
      env: BUILDENV=ubuntu1404-trusty-python3.4
    - os: linux
      dist: trusty
      python: "3.3"
      env: BUILDENV=ubuntu1404-trusty-python3.3
    - os: linux
      dist: trusty
      python: "3.2"
      env: BUILDENV=ubuntu1404-trusty-python3.2
    - os: linux
      dist: trusty
      python: "2.7"
      env: BUILDENV=ubuntu1404-trusty-python2.7
    - os: linux
      dist: trusty
      python: "2.6"
      env: BUILDENV=ubuntu1404-trusty-python2.6

    # Ubuntu 12.04 LTS (Precise Pangolin)
    - os: linux
      dist: precise
      python: "3.6"
      env: BUILDENV=ubuntu1204-precise-python3.6
    - os: linux
      dist: precise
      python: "2.7"
      env: BUILDENV=ubuntu1204-precise-python2.7
    - os: osx
      language: generic
      env: BUILDENV=macos

sudo: false

addons:
  apt:
    packages:
    - ash
    - busybox
    - cabal-install
    - ghc
    - python-pip
    - tcpdump
    - zsh

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.cache/pip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update && brew unlink gnupg && brew install gnupg shellcheck ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    PATH="/usr/local/opt/python/libexec/bin:$PATH" ;
    fi

install:
# Disable shellcheck on Linux, as it is buggy: it fails to parse quotes properly.
# Do so by introducing a symlink to true named "shellcheck" in a directory present in $PATH.
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
    mkdir -pv "$HOME/bin" ;
    ln -sv "$(which true)" "$HOME/bin/shellcheck" ;
    fi
# Install flake8 for the current version of Python, if it is supported.
# Otherwise, keep pycodestyle
  - if python -c 'import sys;sys.exit(sys.version_info[:2] in ((2,6), (3,2), (3,3)))' ; then
    pip install flake8 && flake8 --version ;
    else
    pip install pycodestyle && pycodestyle --version ;
    fi

script:
# Run automated tests
  - ./run_tests.sh
# Install the files after removing conflicting local files
  - rm -f ~/.bash_profile ~/.bash_logout ~/.bashrc ~/.gitconfig ~/.gnupg/gpg.conf ~/.profile ~/.zshrc
  - ./install.sh
# Test updating branch master of the project
  - git remote set-branches origin master
  - git fetch origin
  - test "$TRAVIS_BRANCH" = "master" || git checkout origin/master -b master
  - git checkout "$TRAVIS_BRANCH"
  - ./update.sh
# Finish with a dump of the configuration
  - bin/config-summary

notifications:
  email: false
