# Use http://lint.travis-ci.org/ to check the syntax of this file

language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: "3.6"
    - os: linux
      dist: trusty
      python: "3.5"
    - os: linux
      dist: trusty
      python: "3.4"
    - os: linux
      dist: trusty
      python: "3.3"
    - os: linux
      dist: trusty
      python: "3.2"
    - os: linux
      dist: trusty
      python: "2.7"
    - os: linux
      dist: trusty
      python: "2.6"
    - os: linux
      dist: precise
      python: "3.6"
    - os: linux
      dist: precise
      python: "2.7"
    - os: osx
      language: generic

sudo: false

addons:
  apt:
    packages:
    - ash
    - busybox
    - cabal-install
    - ghc
    - python-pip
    - tcpdump
    - zsh

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.cache/pip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update && brew unlink gnupg && brew install gnupg shellcheck ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    PATH="/usr/local/opt/python/libexec/bin:$PATH" ;
    fi

install:
# Disable shellcheck on Linux, as it is buggy: it fails to parse quotes properly.
# Do so by introducing a symlink to true named "shellcheck" in a directory present in $PATH.
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
    mkdir -pv "$HOME/bin" ;
    ln -sv "$(which true)" "$HOME/bin/shellcheck" ;
    fi
# Install flake8 for the current version of Python, if it is supported.
# Otherwise, keep pycodestyle
  - if python -c 'import sys;sys.exit(sys.version_info[:2] in ((2,6), (3,2), (3,3)))' ; then
    pip install flake8 && flake8 --version ;
    else
    pip install pycodestyle && pycodestyle --version ;
    fi

script:
# Run automated tests
  - ./run_tests.sh
# Install the files after removing conflicting local files
  - rm -f ~/.bash_profile ~/.bash_logout ~/.bashrc ~/.gitconfig ~/.gnupg/gpg.conf ~/.profile ~/.zshrc
  - ./install.sh
# Test updating branch master of the project
  - git remote set-branches origin master
  - git fetch origin
  - test "$TRAVIS_BRANCH" = "master" || git checkout origin/master -b master
  - git checkout "$TRAVIS_BRANCH"
  - ./update.sh
# Finish with a dump of the configuration
  - bin/config-summary

notifications:
  email: false
