#!/bin/sh
# Define aliases and exported variables for every shell

# alias may be unavailable, for example in busybox shell (ash)
if type alias > /dev/null 2>&1 ; then
    # Be verbose! (note: long options may be unavailable)
    alias mkdir='mkdir -v'
    alias mount='mount -v'
    alias umount='umount -v'
    alias ln='ln -v'
    alias rm='rm -v'
    # Be interactive when overwritting files
    alias cp='cp -iv'
    alias mv='mv -iv'
    # Only show changes, if available
    if chmod --help 2>&1 |grep -q '^\s*-c' ; then
        alias chmod='chmod -c'
    else
        alias chmod='chmod -v'
    fi
    if chown --help 2>&1 |grep -q '^\s*-c' ; then
        alias chown='chown -c'
    else
        alias chown='chown -v'
    fi

    # Always use /usr/bin/sudo if available to prevent PATH hijacking
    # sadm alias is for SELinux
    if [ -x /usr/bin/sudo ] ; then
        alias s='/usr/bin/sudo -s'
        alias sadm='/usr/bin/sudo -r sysadm_r -t sysadm_t -s'
    else
        alias s='sudo -s'
        alias sadm='sudo -r sysadm_r -t sysadm_t -s'
    fi

    # Be human !
    alias df='df -h'
    alias du1='du -h --max-depth=1'
    alias du2='du -h --max-depth=2'

    # VIM aliases
    alias :w='echo "Save is not implemented in ${SHELL##*/} :p"'
    alias :x=':w'
    alias :q='echo "Type exit or ^D if you want to exit ${SHELL##*/}"'
    alias :wq='echo "Hey! Thats ${SHELL##*/} and *not* VI(M)!"'

    # List files, using available ls options
    # CFh = columns, classify, human
    LS_PARAMS='-CFh'
    # Option: escape non printable chars (not in busybox ash)
    if ls --help 2>&1 |grep -q -- --escape ; then
        LS_PARAMS="$LS_PARAMS --escape"
    fi
    # Option: use colors
    if ls --help 2>&1 |grep -q -- --color ; then
        LS_PARAMS="$LS_PARAMS --color=always"

        if ls --help 2>&1 |grep -q -- --time-style ; then
            LS_PARAMS="$LS_PARAMS --time-style="$(printf '"+\033[0;35m%%Y-%%m-%%d %%H:%%M\033[0m"')
        fi
    fi
    alias ls="ls $LS_PARAMS"
    alias l='ls'
    alias la='ls -A'
    alias ll='ls -l'
    alias lla='ls -lsA'

    # SELinux aliases
    alias lsz='ls -Z'
    alias llz='ls -lZ'

    # ZSH-specific aliases
    if [ -n "$ZSH_VERSION" ] ; then
        alias lsd='ls -ld *(/)'                 # only show directories
        alias lad='ls -ld .*(/)'                # only show dot-directories
        alias lsa='ls -a .*(.)'                 # only show dot-files
        alias lsd='ls -d *(/)'                  # only show directories
        alias lse='ls -d *(/^F)'                # only show empty directories
        alias lsx='ls -l *(*) | head'           # only show executables
        alias lssuid='ls -l *(s,S) | head'      # only show suid-files
        alias lsbig='ls -lSh *(.) | head'       # display the biggest files
        alias lssmall='ls -Sl *(.) | tail'      # display the smallest files
        alias lsnew='ls -rtl *(.) | tail'       # display the newest files
        alias lsold='ls -rtl *(.) | head'       # display the oldest files

        # Remember where I've been
        alias cd='pushd'
        setopt PUSHD_SILENT
    fi

    # Go to parent directory
    alias ..='cd ..'
    alias ...='cd ../..'

    # Get file attributes, not restricted to "^user\\."
    alias getextattr='getfattr -m - -d'

    # Run restorecon on system folders
    alias restorecon-sys='restorecon -R / -e /home -e /media -e /mnt'

    # List processes
    alias psa='ps -A'
    alias pse='ps -efH'
    alias pss='ps -aux'
    alias psx='ps -AFH'
    alias psz='ps -efZ'
    alias pshz='ps -efHZ'
    alias pstop='ps -eo pid,user,pri,ni,vsz,rsz,stat,pcpu,pmem,time,comm --sort -pcpu'

    # Shortcut to common screen options
    alias scx='screen -x'
    alias scrd='screen -RD'
    alias scls='screen -ls'

    # Clear screen with ESC + c. Ctrl+L may also work.
    alias cls='printf "\033c"'

    # Grep history without writing "h ..." lines into it
    histgrep() {
        fc -l 1 -1 | sed -n "/${1:-.}/s/^ */!/p" | tail -n ${2:-15}
    }
    alias h=' histgrep'

    # Disable history
    alias nohist=' HISTFILE=/dev/null'

    # Options for grep: highlight results and exclude backup files
    # Do not use GREP_OPTIONS so that directly invoking grep does not enable
    # these options (for example with lgrep alias).
    GREP_PARAMS=''
    if grep --help 2> /dev/null |grep -q -- --color ; then
        GREP_PARAMS="$GREP_PARAMS --color=always"
    fi
    if grep --help 2> /dev/null |grep -q -- --exclude ; then
        GREP_PARAMS="$GREP_PARAMS --exclude='*~'"
    fi
    if [ -n "$GREP_PARAMS" ] ; then
        alias grep="grep$GREP_PARAMS"
    fi

    # Find non-ascii characters
    alias grep-noasc="grep -P '[\x80-\xFF]'"

    # Strip commented lines
    alias stripcom="grep -v -E '^[ \r\t]*(#|;|\$)'"

    # Line-buffered grep, useful when selecting output of tail -F
    # Don't use colored output for lgrep
    if grep --help 2> /dev/null |grep -q -- --line-buffered ; then
        if [ -x /usr/bin/grep ] ; then
            alias lgrep='/usr/bin/grep --line-buffered'
        elif [ -x /bin/grep ] ; then
            alias lgrep='/bin/grep --line-buffered'
        else
            alias lgrep='grep --line-buffered'
        fi
    fi

    # Show 3 months by default with cal
    alias cal='cal -3'

    # OpenSSL shortcuts
    # View a certificate request (add -verify to check it)
    alias openssl-csr='openssl req -noout -text -in'
    # View a x509 certificate
    alias openssl-crt='openssl x509 -noout -text -in'
    # View a PKCS#12 file (.pfx or .p12)
    alias openssl-p12='openssl pkcs12 -info -in'
    # Make a SSL connection to IP:port
    alias openssl-connect='openssl s_client -connect'

    # Colored diff
    if which colordiff > /dev/null 2>&1 ; then
        alias diff='colordiff -u'
        # Change svn diff.
        # You may instead put "diff-cmd = colordiff" in ~/.subversion/config
        # Use -x "-u" to show 3 lines of unified context
        # and -x "-u -w" to ignore all white space changes.
        alias svn-diff='svn diff --diff-cmd colordiff'
    else
        alias diff='diff -u'
        alias svn-diff='svn diff'
    fi

    # Diff for patches: all text, new file, show C function, unified context
    alias diff-patch='diff -aNpu'

    # Use most to display man pages using colors
    if which most > /dev/null 2>&1 ; then
        alias man='man -P most'
    fi

    # vman = use vim as a pager
    alias vman="man -P \"/bin/sh -c \\\"col -b -p -x | \
        vim -R \
            -c 'set ft=man nolist nomod nonumber' \
            -c 'map q :q<CR>' \
            -c 'map <SPACE> <C-D>' \
            -c 'map b <C-U>' \
            -\\\"\""

    # Colored dmesg
    if dmesg --help 2> /dev/null |grep -q -- --color ; then
        alias dmesg='dmesg --color'
    fi

    # Use rsync instead of scp
    if which rsync > /dev/null 2>&1 ; then
        # Options: archive, verbose, compress, partial&progress
        alias scp='rsync -avzP'
    fi

    # X Window bell
    if which xset > /dev/null 2>&1 ; then
        alias xbell-off='xset b off'
        alias xbell-on='xset b on'
    fi

    # DNSSEC validation with drill (from ldns package) or dig
    if which drill > /dev/null 2>&1 ; then
        if [ -r '/etc/trusted-key.key' ] ; then
            alias dnssec-check='drill -TD -k /etc/trusted-key.key'
        elif [ -r '/var/lib/unbound/root.key' ] ; then
            alias dnssec-check='drill -TD -k /var/lib/unbound/root.key'
        else
            alias dnssec-check='drill -TD'
        fi
    elif which dig > /dev/null 2>&1 ; then
        if [ -r '/etc/trusted-key.key' ] ; then
            # +multiline can be used to view DNS key id
            alias dnssec-check='dig +sigchase +topdown +trusted-key=/etc/trusted-key.key'
        elif [ -r '/var/lib/unbound/root.key' ] ; then
            alias dnssec-check='dig +sigchase +topdown +trusted-key=/var/lib/unbound/root.key'
        else
            alias dnssec-check='dig +sigchase +topdown'
        fi
    fi

    # View mails in hold queue
    if which postqueue > /dev/null 2>&1 ; then
        alias mailq-hold='postqueue -p |lgrep -E "^[0-9A-F]*!"'
    elif which mailq > /dev/null 2>&1 ; then
        alias mailq-hold='mailq |lgrep -E "^[0-9A-F]*!"'
    fi

    # gitk with all branches
    alias gitka='gitk --all'

    # Add a file to the playlist of the current VLC instance.
    # This setting needs to be set in Preferences->Interface Settings:
    # "Use only one instance when started from file manager"
    alias vlc-append='vlc --started-from-file --playlist-enqueue'

    # hexdump + ascii output, with xxd, od or hexdump
    if which xxd > /dev/null 2>&1 ; then
        alias hexa='xxd'
        alias hexa32='xxd -c32'
    elif which od > /dev/null 2>&1 ; then
        alias hexa='od -tx1z -Ax'
        alias hexa32='od -tx1z -Ax -w32'
    elif which hexdump > /dev/null 2>&1 ; then
        # hexdump command from bsdmainutils package
        # slightly different from "hexdump -C"
        _HEXDUMP_PART1='"%07.7_ax: " 16/1 "%02x ""  "'
        _HEXDUMP_PART2='16/1 "%_p""\n"'
        alias hexa="hexdump -e '$_HEXDUMP_PART1' -e '$_HEXDUMP_PART2'"
        _HEXDUMP_PART1='"%07.7_ax: " 32/1 "%02x ""  "'
        _HEXDUMP_PART2='32/1 "%_p""\n"'
        alias hexa32="hexdump -e '$_HEXDUMP_PART1' -e '$_HEXDUMP_PART2'"
        unset _HEXDUMP_PART1 _HEXDUMP_PART2
    fi

    # Create a Python virtual environment with system packages
    alias virtualenv-sys='virtualenv --system-site-packages'
    alias virtualenv2-sys='virtualenv2 --system-site-packages'
    alias virtualenv3-sys='virtualenv3 --system-site-packages'
fi

# Some functions
# mkdir && cd
mcd() {
    mkdir -p "$1" && cd "$1"
}

# cd && ls
cl() {
    cd "$1" && shift && ls "$@"
}

# Find broken symlinks
if find --help 2> /dev/null |grep -q -- -xtype ; then
    find_broken() {
        find "$@" -xtype l -print
    }
else
    find_broken() {
        find "$@" -type l ! -exec test -e {} \; -print
    }
fi

# Read passwords. Zsh uses "?prompt" option to display a prompt and other
# shells (Bash, Ash, ...) use -p option, so use echo to be compatible.
# Dash fails with "read: Illegal option -s" as this is not POSIX-compliant.
read_pass() {
    echo >&2 -n 'Password: ' && read -s "$@" && echo ''
}

# Generate random passwords from kernel random number generator
# see also: openssl rand -base64 16
gen_pass() {
    # This consumes a lot of random bits, so uses non-blocking urandom and
    # keeps only non-so-special symbols
    tr -cd '0-9a-zA-Z!%&*+,\-./?@^_' < /dev/urandom | head -c"${1:-16}"
    echo ''
}
gen_pass_asc() {
    # Like gen_pass but keeps all ASCII characters.
    tr -cd '!#$%&()*+,\-./0-9:;<=>?@A-Z[\\]^_a-z{|}' < /dev/urandom | head -c"${1:-16}"
    echo ''
}
gen_pass_alnum() {
    # This consume few random bits, so use blocking /dev/random
    # $1 bytes produces ($1 * 4 / 3) base64-character, cut to $1 after dropping
    # non-alphanum symbols.
    head -c"${1:-16}" < /dev/random | base64 -w0 | tr -d '/+=' | head -c"${1:-16}"
    echo ''
}
show_entropy() {
    cat /proc/sys/kernel/random/entropy_avail
}

# Log tail, to have colors when ccze is available
if which ccze > /dev/null 2>&1 ; then
    ltail() {
        tail "$@" |ccze -A
    }
elif type alias > /dev/null 2>&1 ; then
    alias ltail=tail
else
    ltail() {
        tail "$@"
    }
fi

# Convert timestamps from Epoch to dates
epoch2date() {
    if [ $# -ge 1 ] ; then
        while [ $# -ge 1 ] ; do
            date "--date=@$1"
            shift
        done
    else
        echo >&2 "Usage: epoch2date TIMESTAMP [...]"
    fi
}
epoch2utc() {
    if [ $# -ge 1 ] ; then
        while [ $# -ge 1 ] ; do
            date -u "--date=@$1"
            shift
        done
    else
        echo >&2 "Usage: epoch2utc TIMESTAMP [...]"
    fi
}
# Get the number of seconds since Epoch
date_epoch() {
    date '+%s'
}

# Retrieve HTTPS certificate of a website
get_https_cert() {
    openssl s_client -servername "$1" -connect "$1:443" < /dev/null \
         -showcerts | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
}

# Combine postcat with less
postless() {
    local OUTPUT
    OUTPUT="$(postcat "$@")"
    # Use less only if postcat succeded
    if [ "$?" -eq 0 ] ; then
        echo "$OUTPUT" |less
    else
        echo "$OUTPUT"
    fi
}

# Highlight a pattern, if grep accept colors
if grep --help 2> /dev/null |grep -q -- --color ; then
    if [ -n "$BASH_VERSION" -o -n "$ZSH_VERSION" ] ; then
        # Modern shells support array substitution
        hl() {
            grep -E --color=always -e '' "${@/#/-e}"
        }
    else
        # Same function, with a temporary file
        hl() {
            FILE="$(mktemp)"
            trap '/bin/rm -f "$FILE"' EXIT HUP INT QUIT TERM
            while [ $# -ge 1 ] ; do
                echo "$1" >> "$FILE"
                shift
            done
            grep -E --color=always -e '' -f "$FILE"
            /bin/rm "$FILE"
        }
    fi
fi

# Enhance the output of "mount"
mounttable() {
    mount | LC_ALL=C sort -k3 | column -t
}

# Print args or use standard input (mainly for internal use)
print_args_or_stdin() {
    if [ $# -eq 0 -o "$1" = "-" ] ; then
        cat
    else
        while [ $# -ge 1 ] ; do
            echo "$1"
            shift
        done
    fi
}

# Reverse hex string and dump it
if which xxd > /dev/null 2>&1 ; then
    revhex() {
        print_args_or_stdin "$@" | xxd -p -r | xxd
    }
fi

# Reverse base64 and dump with "hexa" alias
if type alias > /dev/null 2>&1 ; then
    base6416() {
        print_args_or_stdin "$@" | base64 -d | hexa
    }
fi

# Convert decimal to hexadecimal and vice-versa
dechex() {
    (echo 'obase=16' ; print_args_or_stdin "$@") | bc -q | tr '[A-F]' '[a-f]'
}
hexdec() {
    (echo 'ibase=16' ; (print_args_or_stdin "$@" | tr '[a-f]' '[A-F]')) | bc -q
}

# Sort domain names by their subdomains
dnssort() {
    # Reverse dot-separated components
    sed '/\n/!G;s/\([^.]*\)\.\(.*\n\)/&\2.\1/;//D;s/\n//' | \
        sort "$@" | \
        sed '/\n/!G;s/\([^.]*\)\.\(.*\n\)/&\2.\1/;//D;s/\n//'
}

# Some X-Window functions
xwinlist() {
    xwininfo -root -tree
}
xwinpid() {
    xprop _NET_WM_PID | sed 's/.*= *//'
}

# Trace process executions
strace_exec() {
    strace -s 65536 -qq -e execve -e signal=none -f "$@" 2>&1 | grep -v ' = -1 ENOENT ([^)]*)$'
}
