#!/bin/sh
# Define environment variables to customize the command line interface

# Find real home directory
# Try sudo user
if [ -z "$REAL_HOME" ] && [ -n "$SUDO_USER" ] ; then
    REAL_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
fi
# Use current $HOME variable
if [ -z "$REAL_HOME" ] ; then
    REAL_HOME="$HOME"
fi
export REAL_HOME

# Set email address from .email file, if available
if [ -r "$REAL_HOME/.email" ] ; then
    export EMAIL=$(cat "$REAL_HOME/.email")
fi

# Ensure that all bin and sbin folders are in PATH, if they are not symlinks
for DIR in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin ; do
    if [ ! -L "$DIR" -a -d "$DIR" ] && ! (echo ":$PATH:" | grep -q ":$DIR:" ) ; then
        export PATH="$DIR:$PATH"
    fi
done

# Add home in path
HOMEBIN="$REAL_HOME/bin"
if [ -d "$HOMEBIN" ] && ! (echo ":$PATH:" | grep -q ":$HOMEBIN:" ) ; then
    export PATH="$HOMEBIN:$PATH"
fi
unset HOMEBIN

# Python configuration
if [ -r "$REAL_HOME/.pythonrc" ] ; then
    export PYTHONSTARTUP="$REAL_HOME/.pythonrc"
fi

# Prevent Erase in Line (EL) to Right (\33[K) in the colored output of grep.
# Please read grep man page for further information.
export GREP_COLORS='ne'

# Use Vim
if which vim > /dev/null 2> /dev/null ; then
    export EDITOR='/usr/bin/vim'
fi

# Use less
if which less > /dev/null 2> /dev/null ; then
    # Force -R = --RAW-CONTROL-CHARS to have colors in less
    export LESS='-R'
    export LESSCOLOR='yes'
    export PAGER='less -R'
    # -R = --quit-if-one-screen, -X = --no-init
    export GIT_PAGER='less -RFX'
fi

# Make less more friendly for non-text input files, see lesspipe(1)
if [ -x /usr/bin/lesspipe ] ; then
    export LESSOPEN="| /usr/bin/lesspipe %s"
    export LESSCLOSE="/usr/bin/lesspipe %s %s"
fi
