#!/bin/sh
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2014-2023 Nicolas Iooss
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Define useful shell functions

# mkdir && cd
mcd() {
    # shellcheck disable=SC2164
    mkdir -p "$1" && cd "$1"
}

# cd && ls
cl() {
    cd "$1" && shift && ls "$@"
}

# Find broken symlinks
# shellcheck disable=SC2185
case $(find --help 2> /dev/null) in
    *-xtype*)
        find_broken() {
            find "$@" -xtype l -print
        }
        ;;
    *)
        find_broken() {
            # shellcheck disable=SC2039
            find "$@" -type l ! -exec test -e {} \; -print
        }
        ;;
esac

# Find empty directories
find_empty() {
    find "$@" -type d -empty -print
}

# Compute size of subdirectories and sort them
dus() {
    du -h "$@" | sort -h
}
du1s() {
    du -h --max-depth=1 "$@" | sort -h
}
du2s() {
    du -h --max-depth=2 "$@" | sort -h
}

# Read passwords. Zsh uses "?prompt" option to display a prompt and other
# shells (Bash, Ash, ...) use -p option, so use echo to be compatible.
# Dash fails with "read: Illegal option -s" as this is not POSIX-compliant.
read_pass() {
    # shellcheck disable=SC2039,SC3045
    printf >&2 'Password: ' && read -r -s "$@" && echo ''
}

# Generate random passwords from kernel random number generator
# see also: openssl rand -base64 16
gen_pass() {
    # This consumes a lot of random bits, so uses non-blocking urandom and
    # keeps only non-so-special symbols
    tr -cd '0-9a-zA-Z!%&*+,\-./?@^_' < /dev/urandom | head -c"${1:-16}"
    echo ''
}
gen_pass_asc() {
    # Like gen_pass but keeps all ASCII characters.
    tr -cd '!#$%&()*+,\-./0-9:;<=>?@A-Z[\\]^_a-z{|}' < /dev/urandom | head -c"${1:-16}"
    echo ''
}
gen_pass_alnum() {
    # This consume few random bits, so use blocking /dev/random
    # $1 bytes produces ($1 * 4 / 3) base64-character, cut to $1 after dropping
    # non-alphanum symbols.
    head -c"${1:-16}" < /dev/random | base64 -w0 | tr -d '/+=' | head -c"${1:-16}"
    echo ''
}
show_entropy() {
    cat /proc/sys/kernel/random/entropy_avail
}

# Log tail, to have colors when ccze is available
# shellcheck disable=SC2039
if command -v ccze > /dev/null 2>&1 ; then
    ltail() {
        tail "$@" |ccze -A
    }
elif type alias > /dev/null 2>&1 ; then
    alias ltail=tail
else
    ltail() {
        tail "$@"
    }
fi

# Convert timestamps from Epoch to dates
epoch2date() {
    if [ $# -ge 1 ] ; then
        while [ $# -ge 1 ] ; do
            date "--date=@$1"
            shift
        done
    else
        echo >&2 "Usage: epoch2date TIMESTAMP [...]"
    fi
}
epoch2utc() {
    if [ $# -ge 1 ] ; then
        while [ $# -ge 1 ] ; do
            date -u "--date=@$1"
            shift
        done
    else
        echo >&2 "Usage: epoch2utc TIMESTAMP [...]"
    fi
}
# Get the number of seconds since Epoch
date_epoch() {
    date '+%s'
}
# Dump the local timezone file
tzdump() {
    if [ $# -ge 1 ] ; then
        while [ $# -ge 1 ] ; do
            if [ -r "/usr/share/zoneinfo/$1" ] ; then
                zdump -v "/usr/share/zoneinfo/$1"
            else
                echo >&2 "Unknown zone info $1."
                return 1
            fi
            shift
        done
    elif [ -L /etc/localtime ] ; then
        zdump -v "$(readlink -f /etc/localtime)"
    elif [ -r /etc/localtime ] ; then
        zdump -v /etc/localtime
    else
        zdump -v /usr/share/zoneinfo/UTC
    fi | sed 's,^/usr/share/zoneinfo/,,'
}

# Retrieve HTTPS certificate of a website
get_https_cert() {
    openssl s_client -servername "$1" -connect "$1:443" < /dev/null \
         -showcerts | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
}
get_https_cert_proxy() {
    # shellcheck disable=SC3043
    local S_CLIENT_PROXY
    S_CLIENT_PROXY="$(
        printf %s\\n%s\\n%s\\n%s\\n \
            "${https_proxy-}" \
            "${HTTPS_PROXY-}" \
            "${all_proxy-}" \
            "${ALL_PROXY-}" \
            | \
        sed -n 's,^\(http://\)\?\([0-9a-zA-Z._-]\+:[0-9]\+\)\(/\)\?$,\2,p' | \
        sed -n 1p)"
    if [ -z "$S_CLIENT_PROXY" ] ; then
        echo >&2 "Unable to parse HTTPS proxy settings"
        return 1
    fi
    openssl s_client -servername "$1" -connect "$1:443" < /dev/null \
         -proxy "$S_CLIENT_PROXY" \
         -showcerts | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
}

# Check the DANE configuration for a HTTPS website (cert and TLSA DNS record)
# To get a TLS record, use something like:
#   dig TLSA _443._tcp.good.dane.verisignlabs.com
check_https_dane() {
    gnutls-cli --dane --ca-verification --ocsp --port 443 "$1" < /dev/null
}

# Combine postcat with less
postless() {
    # shellcheck disable=SC3043
    local DIR OUTPUT STATUS
    if [ $# -eq 1 ] && ! [ -e "$1" ] ; then
        # Find message by ID in Postfix spool
        for DIR in /var/spool/postfix/* /var/spool/postfix/*/* ; do
            [ -d "$DIR" ] || continue
            # Avoid the defer folder which contains text files
            [ "${DIR%/*}" != "/var/spool/postfix/defer" ] || continue
            if [ -e "$DIR/$1" ] ; then
                set "$DIR/$1"
                break
            fi
        done
    fi
    OUTPUT="$(postcat "$@")"
    STATUS=$?
    # Use less only if postcat succeeded
    if [ "$STATUS" -eq 0 ] ; then
        printf %s\\n "$OUTPUT" |less
    else
        printf %s\\n "$OUTPUT"
        return $STATUS
    fi
}

# Highlight a pattern, if grep accept colors
case $(grep --help 2> /dev/null) in
    *--color*)
        if [ -n "${BASH_VERSION:-}" ] || [ -n "${ZSH_VERSION:-}" ] ; then
            # Modern shells support array substitution
            hl() {
                # shellcheck disable=SC3060
                \grep -E --color=always -e '' "${@/#/-e}"
            }
        else
            # Same function, with a temporary file
            hl() {
                # shellcheck disable=SC3043
                local FILE
                FILE="$(mktemp)"
                # shellcheck disable=SC2064
                trap "/bin/rm -f -- \"$FILE\"" EXIT HUP INT QUIT TERM
                while [ $# -ge 1 ] ; do
                    printf %s\\n "$1" >> "$FILE"
                    shift
                done
                \grep -E --color=always -e '' -f "$FILE"
                /bin/rm -- "$FILE"
            }
        fi
        ;;
esac

# Find a literal string in UTF-16 file (for example from Windows)
utf16grep() {
    # shellcheck disable=SC3043
    local PATTERN
    PATTERN="$(printf '%s' "$1" | iconv -f utf-8 -t utf-16le | hexdump -e '/1 "x%02x"' | sed 's/x/\\x/g')"
    shift
    grep -a -P "$PATTERN" "$@"
}

# Escape control characters when cat'ing binary streams to a TTY
# Automatically add -v (for --show-nonprinting) to cat parameters.
# This is known to be incompatible with busybox cat, which is detected by
# testing whether /bin/cat is a symbolic link.
protected_cat() {
    python -c \
        'import os,sys;a=sys.argv;os.execv(a[1],["cat","-v"][:1+sys.stdout.isatty()]+a[2:])' \
        "$@"
}
if [ -x /usr/bin/python ] || command -v python > /dev/null 2>&1 ; then
    if [ -x /usr/bin/cat ] ; then
        if ! [ -L /usr/bin/cat ] ; then
            cat() {
                protected_cat /usr/bin/cat "$@"
            }
        fi
    elif [ -x /bin/cat ] ; then
        if ! [ -L /bin/cat ] ; then
            cat() {
                protected_cat /bin/cat "$@"
            }
        fi
    fi
fi

# Enhance the output of "mount" by aligning columns.
# "findmnt" from util-linux project produces nicer output.
mounttable() {
    mount | LC_ALL=C sort -k3 | column -t
}

# Convert a VMDK disk image to a RAW one
vmdk2raw() {
    if [ $# -ne 1 ] ; then
        echo >&2 "Usage: $0 image.vmdk"
        echo >&2 "Convert image.vmdk to image.vmdk.converted.raw"
        return 1
    fi
    qemu-img convert -f vmdk -O raw "$1" "$1.converted.raw"
}

# Convert a QCOW2 disk image to a RAW one
qcow2raw() {
    if [ $# -ne 1 ] ; then
        echo >&2 "Usage: $0 image.qcow2"
        echo >&2 "Convert image.qcow2 to image.qcow2.converted.raw"
        return 1
    fi
    qemu-img convert -f qcow2 -O raw "$1" "$1.converted.raw"
}

# Print args or use standard input (mainly for internal use)
print_args_or_stdin() {
    if [ $# -eq 0 ] || [ "$1" = "-" ] ; then
        cat
    else
        while [ $# -ge 1 ] ; do
            printf %s\\n "$1"
            shift
        done
    fi
}

# Reverse hex string and dump it
if [ -x /usr/bin/xxd ] || command -v xxd > /dev/null 2>&1 ; then
    revhex() {
        print_args_or_stdin "$@" | xxd -p -r | xxd
    }
fi

# Reverse base64 and dump with "hexa" alias
# shellcheck disable=SC2039
if type alias > /dev/null 2>&1 ; then
    base6416() {
        print_args_or_stdin "$@" | base64 -d | hexa
    }
fi

# Pretty-print some filetypes
if [ -x /usr/bin/python ] || command -v python > /dev/null 2>&1 ; then
    pretty_json() {
        # Use Python's json module
        cat "$@" | python -m json.tool
    }
else
    pretty_json() {
        # Use Perl's json_pp
        cat "$@" | json_pp
    }
fi
pretty_xml() {
    # Use xmllint from libxml2
    cat "$@" | xmllint --format -
}

# Convert decimal to hexadecimal and vice-versa
dechex() {
    (echo 'obase=16' ; print_args_or_stdin "$@") | bc -q | tr 'A-F' 'a-f'
}
hexdec() {
    (echo 'ibase=16' ; (print_args_or_stdin "$@" | tr 'a-f' 'A-F')) | bc -q
}

# Recursive md5sum, sha1sum, sha256sum... in directories
md5sumd() {
    # shellcheck disable=SC2039
    find "$@" -type f -exec md5sum {} +
}
sha1sumd() {
    # shellcheck disable=SC2039
    find "$@" -type f -exec sha1sum {} +
}
sha224sumd() {
    # shellcheck disable=SC2039
    find "$@" -type f -exec sha224sum {} +
}
sha256sumd() {
    # shellcheck disable=SC2039
    find "$@" -type f -exec sha256sum {} +
}
sha384sumd() {
    # shellcheck disable=SC2039
    find "$@" -type f -exec sha384sum {} +
}
sha512sumd() {
    # shellcheck disable=SC2039
    find "$@" -type f -exec sha512sum {} +
}

# Decode ASN.1 structures with OpenSSL, from the file given as argument or stdin
# DER encoding can be binary, hexadecimal or base64
openssl_asn1der() {
    if [ $# -eq 0 ] ; then
        openssl asn1parse -inform DER -i -dump
    else
        openssl asn1parse -inform DER -i -dump -in "$@"
    fi
}
openssl_asn1hex() {
    print_args_or_stdin "$@" | xxd -p -r | openssl asn1parse -inform DER -i -dump
}
openssl_asn1b64() {
    print_args_or_stdin "$@" | base64 -d | openssl asn1parse -inform DER -i -dump
}

# Sort domain names by their subdomains
dnssort() {
    # Reverse dot-separated components
    sed '/\n/!G;s/\([^.]*\)\.\(.*\n\)/&\2.\1/;//D;s/\n//' | \
        LANG=C sort "$@" | \
        sed '/\n/!G;s/\([^.]*\)\.\(.*\n\)/&\2.\1/;//D;s/\n//'
}

# Sort IPv4 addresses
ipv4sort() {
    sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4 "$@"
}

# Get the public IP address used by default, through HTTP or DNS
# http://ifconfig.me/ is not used as it is not HTTPS
public_ipv4_dns() {
    if [ -x /usr/bin/dig ] || command -v dig > /dev/null 2>&1 ; then
        dig +short -4 -t A myip.opendns.com @resolver1.opendns.com
    elif [ -x /usr/bin/host ] || command -v host > /dev/null 2>&1 ; then
        LANG=C host myip.opendns.com resolver1.opendns.com | \
            sed -n 's/^myip\.opendns\.com has address //p'
    else
        echo >&2 'could not find commands dig or host'
        return 1
    fi
}
public_ipv6_dns() {
    if [ -x /usr/bin/dig ] || command -v dig > /dev/null 2>&1 ; then
        dig +short -6 -t AAAA myip.opendns.com @resolver1.ipv6-sandbox.opendns.com
    elif [ -x /usr/bin/host ] || command -v host > /dev/null 2>&1 ; then
        LANG=C host -6 -t AAAA myip.opendns.com resolver1.ipv6-sandbox.opendns.com | \
            sed -n 's/^myip\.opendns\.com has IPv6 address //p'
    else
        echo >&2 'could not find commands dig or host'
        return 1
    fi
}
public_ipv4_https() {
    # https://ipv4.wtfismyip.com/json is also possible
    # https://ipinfo.io/ip too
    curl --silent -4 'https://myipv4.p1.opendns.com/get_my_ip' | sed 's/^{"ip":"\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)"}$/\1/'
}
public_ipv6_https() {
    # https://ipv6.wtfismyip.com/json is also possible
    curl --silent -6 'https://myipv6.p1.opendns.com/get_my_ip' | sed 's/^{"ip":"\([0-9a-f:]\+\)"}$/\1/'
}
# Test the functions above
all_public_ips() {
    echo "public_ipv4_dns: $(public_ipv4_dns)"
    echo "public_ipv4_https: $(public_ipv4_https)"
    echo "public_ipv6_dns: $(public_ipv6_dns)"
    echo "public_ipv6_https: $(public_ipv6_https)"
}

# Get the local printers using mDNS
query_mdns_printers() {
    # 224.0.0.251 is multicast mDNS. It is also possible to query a target IP directly
    # A printer will reply to _printer._tcp.local with:
    # - a PTR record for _printer._tcp.local to NAME._printer._tcp.local
    # - a SRV record for NAME._printer._tcp.local which targets NAME.local
    # - possibly a TXT record for NAME._printer._tcp.local with additional information
    # - A and AAAA records for NAME.local to get its IP addresses
    #
    # _printer port is 515 (Spooler), _ipp and _ipps port is 631 (IPP) and _pdl-datastream port is 9100 (JetDirect)
    #
    # Specifications: https://developer.apple.com/bonjour/printing-specification/bonjourprinting-1.2.1.pdf
    dig @224.0.0.251 -p 5353 -t PTR _printer._tcp.local. _ipp._tcp.local. _ipps._tcp.local. _pdl-datastream._tcp.local. | \
        grep -v -e '^;' -e '^$'
}

# Some X-Window functions
xwinlist() {
    xwininfo -root -tree
}
xwinpid() {
    xprop _NET_WM_PID | sed 's/.*= *//'
}

# Open file within a X Desktop environment (see xdg-mime command for configuration)
xo() {
    # By default open the current directory
    if [ $# -eq 0 ] ; then
        xdg-open .
    else
        xdg-open "$@"
    fi
}

# Use webcam with mplayer
mplayer_webcam() {
    mplayer tv:// -tv driver=v4l2:device=/dev/video0:width=640:height=480
}

# Trace process executions
strace_exec() {
    # shellcheck disable=SC3043
    local SYSCALLS
    SYSCALLS='execve'
    # Trace execveat if it is known by strace
    if strace -qq -e execveat true 2> /dev/null
    then
        SYSCALLS="$SYSCALLS,execveat"
    fi
    # Run the program without modifying its stdin/out/err streams
    ( \
        ( \
            strace -s 65536 -e "$SYSCALLS" -e signal=none -o /proc/self/fd/3 \
                -f "$@" >&4 \
        ) 3>&1 | \
        \grep -v >&2 \
            -e '^[0-9]\+ \+execve\(at\)\?(.*) = -1 ENOENT ([^)]*)$' \
            -e '^[0-9]\+ \++++ exited with [0-9]\+ +++$' \
    ) 4>&1
}

# Find the package which provides an installed command
# shellcheck disable=SC2230
if [ -x /usr/bin/which ] ; then
    if [ -x /sbin/apk ] ; then
        # Alpine Linux
        whichpkg() {
            /usr/bin/which "$@" | xargs apk info --who-owns
        }
    elif [ -x /usr/bin/pacman ] ; then
        # Arch Linux
        whichpkg() {
            /usr/bin/which "$@" | xargs pacman -Q --owns
        }
    elif [ -x /usr/bin/dpkg ] ; then
        # Debian
        whichpkg() {
            /usr/bin/which "$@" | while IFS= read -r FILEPATH ; do
                if ! dpkg --search "$FILEPATH" ; then
                    # On Ubuntu 20.04, /bin is a symlink to /usr/bin but
                    # packages still install programs in /bin (such as grep)
                    BINFILEPATH="$(printf %s "$FILEPATH" | sed -n 's:^/usr/bin/:/bin/:p')"
                    if [ -L /bin ] && [ -n "$BINFILEPATH" ] && [ -e "$BINFILEPATH" ] ; then
                        dpkg --search "$BINFILEPATH"
                    else
                        # Propagate the error to the caller
                        false
                    fi
                fi
            done
        }
    elif [ -x /usr/bin/qfile ] ; then
        # Gentoo
        whichpkg() {
            /usr/bin/which "$@" | xargs qfile
        }
    elif [ -x /usr/local/bin/brew ] ; then
        # Mac OS X files are symlinks to /usr/local/Cellar/PKGNAME/...
        whichpkg() {
            /usr/bin/which "$@" | xargs realpath
        }
    elif [ -x /bin/rpm ] ||  [ -x /usr/bin/rpm ] ; then
        # Redhat
        whichpkg() {
            /usr/bin/which "$@" | xargs rpm -q --file
        }
    fi
fi

# Edit the list of ignored files in SVN (takes a directory as parameter)
svn_editign() {
    if [ $# = 0 ] ; then
        # Use current directory by default
        set .
    fi
    svn propedit svn:ignore "$@"
}

# Create an archive from the current git repository to the given path
gitarc() {
    # shellcheck disable=SC3043
    local ARCPATH ARCFILE FORMAT
    ARCPATH="$1"
    if [ -z "$ARCPATH" ] ; then
        ARCPATH="$(git rev-parse --show-toplevel).tar.gz"
        if [ -z "$ARCPATH" ] ; then
            echo >&2 "Unable to build a path to created archive"
            return 1
        fi
        echo >&2 "Creating archive in $ARCPATH"
    fi
    ARCFILE="${ARCPATH##*/}"
    case "$ARCFILE" in
        *.tar)
            FORMAT=tar
            ;;
        *.tar.gz)
            FORMAT=tar.gz
            ;;
        *.tar.xz)
            FORMAT=tar.xz
            ;;
        *.tgz)
            FORMAT=tgz
            ;;
        *.zip)
            FORMAT=zip
            ;;
        *)
            echo >&2 "Unknown file type for $ARCFILE"
            return 1
    esac
    git -C "$(git rev-parse --show-toplevel)" archive \
        --format="$FORMAT" --output="$ARCPATH" \
        --prefix="${ARCFILE%."$FORMAT"}/" HEAD
}

# Override objdump to write stdin to a temporary file if no file is provided in
# the arguments, because objdump only operated on regular files.
objdump_wrapper() {
    # shellcheck disable=SC3043
    local ARG RETVAL TARGET TEMPFILE
    TARGET="$1"
    shift
    for ARG in "$@"
    do
        if [ "${ARG#-}" = "$ARG" ] || [ "$ARG" = "--" ]
        then
            # ARG begins with a dash or is -- indicated there is a file
            "$TARGET" "$@"
            return $?
        fi
    done

    # There is no file, let's create one
    TEMPFILE="$(mktemp /tmp/objdump.XXXXXXXXXX)"
    # shellcheck disable=SC2064
    trap "/bin/rm -f \"$TEMPFILE\"" EXIT HUP INT QUIT TERM
    cat > "$TEMPFILE"
    "$TARGET" "$@" "$TEMPFILE"
    RETVAL=$?
    /bin/rm -f "$TEMPFILE"
    return $RETVAL
}

# Use aliases if available, and because dash are allowed in their names
# shellcheck disable=SC2039
if type alias > /dev/null 2>&1 ; then
    alias objdump='objdump_wrapper /usr/bin/objdump'
    alias arm-none-eabi-objdump='objdump_wrapper /usr/bin/arm-none-eabi-objdump'
    alias aarch64-linux-gnu-objdump='objdump_wrapper /usr/bin/aarch64-linux-gnu-objdump'
else
    objdump() {
        objdump_wrapper /usr/bin/objdump "$@"
    }
fi

# Use Google Translate to speak, when espeak is not installed
# Source: https://twitter.com/climagic/status/580751523048734720
googlesay() {
    curl -s \
        -A 'Mozilla/5.0 (Linux; U; Android; en-us) AppleWebKit/999+ (KHTML, like Gecko) Safari/999.9' \
        'https://translate.google.com/translate_tts' \
        -d "tl=en&q=$*" | \
    mpg123 -q -
}
