#!/bin/sh
# Prompt
# Ubuntu monochrome: '\u@\h:\w\$ '
# Ubuntu with colors: '\[\033[1;32m\]\u@\h\[\033m\]:\[\033[1;34m\]\w\[\033[m\]\$ '
# Arch default: '[\u@\h \W]\$ '
# Busybox sh: $

# Color rules:
# * bold red for root, yellow otherwise
# * green for local machine, pink for remote host
# * magenta/purple for working directory
if [ `id -u` = 0 ] ; then
    BASH_PROMPT_USER='\[\e[1;31m\]\u\[\e[m\]'
    ZSH_PROMPT_USER='%B%F{red}%n%f%b'
else
    BASH_PROMPT_USER='\[\e[33m\]\u\[\e[m\]'
    ZSH_PROMPT_USER='%F{yellow}%n%f'
fi

if [ "x$SSH_CLIENT" = x ]; then
    BASH_PROMPT_HOST='\[\e[32m\]\h\[\e[m\]'
    ZSH_PROMPT_HOST='%F{green}%m%f'
else
    BASH_PROMPT_HOST='\[\e[36m\]\h\[\e[m\]'
    ZSH_PROMPT_HOST='%F{pink}%m%f'
fi


if [ ! -z "$BASH_VERSION" ]; then
    # Don't forget \[...\] to compute prompt width correctly
    PS1="$BASH_PROMPT_USER@$BASH_PROMPT_HOST \[\e[35m\]\w\[\e[m\]\\\$ "
    # Set the title to user@host:dir
    case "$TERM" in
        xterm*|rxvt*)
            PS1="\[\e]0;\u@\h: \w\a\]$PS1"
            ;;
    esac
elif [ ! -z "$ZSH_VERSION" ]; then
    PROMPT="$ZSH_PROMPT_USER@$ZSH_PROMPT_HOST %F{magenta}%~%f%# "
    # Display last returned value at the beginning of the prompt
    PROMPT="%(?..%F{red}[%?]%f )$PROMPT"
    # Right prompt with date
    RPROMPT="%F{cyan}%D{%d/%m} %T%f"
    case "$TERM" in
        xterm*|rxvt*)
            PROMPT=$'%{\e]0;%n@%m: %~\a%}'"$PROMPT"
            ;;
    esac
fi

unset BASH_PROMPT_USER ZSH_PROMPT_USER
unset BASH_PROMPT_HOST ZSH_PROMPT_HOST
